BASE_URL = 'https://qa-scooter.praktikum-services.ru/'
CREATE_COURIERS_URL = 'api/v1/courier'
LOGIN_COURIERS_URL = '/api/v1/courier/login'
DELETE_COURIERS_URL = '/api/v1/courier/'
CREATE_ORDER_URL = '/api/v1/orders'
GET_ORDER_LIST_URL = '/api/v1/orders'
